version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mykare-postgres
    environment:
      spring.datasource.url: jdbc:postgresql://mykare-postgres:5432/mydatabase
      spring.datasource.username: postgres
      spring.datasource.password: postgres
      spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect

  mykare-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
